### ISSUE TITLE
Manque de domaines de traduction

### ISSUE THREAD

**Issue by Rahe** [BeAPI/bea-acf-wp-forms#3]
Il manque les domaines de traduction sur ces lignes 

- https://github.com/BeAPI/bea-acf-wp-forms/blob/master/bea-acf-wp-forms.php#L26
- https://github.com/BeAPI/bea-acf-wp-forms/blob/master/wp_forms-v5.php#L22

**Comment by MaximeCulea** [comment]
Fixed with [1.1.0](https://github.com/BeAPI/bea-acf-wp-forms/releases/tag/1.1.0) release!
